################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
################ Chinese language ##################
[zh-cn]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh-cn"
weight = 1